apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 05-kernelarg-slub
spec:
  config:
    ignition:
      version: 3.1.0
  kernelArguments:
    - slub_max_order=0
