apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cluster
spec:
  domain: apps.p1293.cecc.ihost.com
  loadBalancer:
    platform:
      type: ""
status:
  defaultPlacement: ControlPlane
