apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: sysctl-pmtu-tuning
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - name: sysctl-pmtu-tuning
      data: |
        [main]
        summary=Tune sysctl pmtu parameters
        [sysctl]
        net.ipv4.ip_no_pmtu_disc=1
        net.ipv4.route.min_pmtu=1450
  recommend:
    - match:
        - label: node-role.kubernetes.io/master
        - label: node-role.kubernetes.io/worker
      priority: 10
      profile: sysctl-pmtu-tuning
